### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by purpleidea** [jordanorelli/moon#8]
Hi @jordanorelli I like what you've done here, cool :)

Any chance you can throw a license file into this repo so others can patch/modify/etc without fear of legal repercussions?

If you're unsure about licensing, a good choice for a lib like this might be the LGPL version 3+. It protects you, but also lets others use it.
I'm not a lawyer, but I'm happy to answer any questions you have about this, or write the patch.

Thanks!
James

**Comment by jordanorelli** [comment]
sure, I'll look into it and post one in a bit.

**Comment by purpleidea** [comment]
Awesome, thanks!

**Comment by jordanorelli** [comment]
Added a license (MIT license) in the LICENSE file. Should be all set now.

**Comment by purpleidea** [comment]
Cool, thanks!
